
SETLOCAL

CALL container-config

CALL :DO_BACKUP %CONTAINER_GROUP%-sql-server-1 %CONTAINER_DATABASE_NAME% %CONTAINER_DATABASE_USER% %CONTAINER_DATABASE_PASSWORD%

ENDLOCAL
EXIT /B
GOTO :EOF

:DO_BACKUP

SET CONTAINER_NAME=%1
SET DATABASE_NAME=%2
SET DATABASE_USER_NAME=%3
SET DATABASE_USER_PASSWORD=%4

ECHO --Backing Up %DATABASE_NAME%

docker exec -it %CONTAINER_NAME% ^
/opt/mssql-tools18/bin/sqlcmd -S localhost -U %DATABASE_USER_NAME% -P %DATABASE_USER_PASSWORD% -C ^
-Q "BACKUP DATABASE [%DATABASE_NAME%] TO DISK = N'/var/opt/mssql/backups/%DATABASE_NAME%.bak' WITH INIT, STATS=10;"

docker cp %CONTAINER_NAME%:/var/opt/mssql/backups/%DATABASE_NAME%.bak %DATABASE_NAME%.bak
EXIT /B
