
IF EXIST "%CUDA_PATH%"=="" (
    SET APP_MODE=gpu
) ELSE (
    IF EXIST "%PROGRAMFILES%\NVIDIA Corporation" (
        SET APP_MODE=gpu
    )
)

SET CONTAINER_GROUP=test-project
SET CONTAINER_DATABASE_NAME=test_database
SET CONTAINER_DATABASE_USER=test_database
SET CONTAINER_DATABASE_PASSWORD=test_database

IF "%APP_PROJECT%"=="" SET APP_PROJECT=%CONTAINER_GROUP%
IF "%APP_MODE%"=="" SET APP_MODE=cpu
