
IF EXIST "%CUDA_PATH%"=="" (
    SET APP_MODE=cuda
) ELSE (
    IF EXIST "%PROGRAMFILES%\NVIDIA Corporation" (
        SET APP_MODE=cuda
    )
)

SET CONTAINER_GROUP=test-project

SET CONTAINER_DATABASE_NAME=test_database
SET CONTAINER_DATABASE_USER=test_database
SET CONTAINER_DATABASE_PASSWORD=test_database

SET CONTAINER_OLLAMA_NAME=ollama
SET CONTAINER_OLLAMA_MODELS=phi3 llama3.2 llava-phi3

SET EXTRA_ARGS=

IF "%APP_PROJECT%"=="" SET APP_PROJECT=%CONTAINER_GROUP%
IF "%APP_MODE%"=="" SET APP_MODE=cpu
