
services:
  jupyterlab:
    container_name: jupyterlab
    build:
        dockerfile: DockerFile.jupyterlab
        context: .
    ports:
      - "8888:8888"
    volumes:
      - jupyterlab-working:/jupyter/src