FROM mcr.microsoft.com/mssql/server:2019-latest

RUN mkdir /var/opt/mssql/bin 
RUN mkdir /var/opt/mssql/backups 
# COPY ./publish/sqlclr/project.* /var/opt/mssql/bin

USER root
RUN chown mssql /var/opt/mssql/bin --recursive
RUN chown mssql /var/opt/mssql/backups --recursive

USER mssql

CMD ["/opt/mssql/bin/sqlservr"]