services:
  sql-server:
    extends:
      file: docker-compose.sql-server.yml
      service: sql-server
    networks:
      - backend

  sql-sonarqube:
    extends:
      file: docker-compose.sonarqube.yml
      service: sonarqube
    networks:
      - backend

  apache-tika:
    extends:
      file: docker-compose.apache-tika.yml
      service: apache-tika
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
     sqlserver-data:
     sonarqube-data:
     sonarqube-extensions:
     sonarqube-logs: