FROM quay.io/keycloak/keycloak:latest

# Copy the import file to the appropriate directory
COPY ./keycloak/${KEYCLOAK_IMPORT} /opt/keycloak/data/import/

# Expose the necessary port
EXPOSE 8080

# Use ENTRYPOINT and CMD to pass environment variables correctly
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
CMD ["--import-realm", "/opt/keycloak/data/import/${KEYCLOAK_IMPORT}", "--verbose"]
