name: sql-server
services:
    sql-server:
        build:
            dockerfile: DockerFile.sql-server-2019
            context: .
        ports:
        - 1433:1433
        environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=test_database
        volumes:
        - sqlserver-data:/var/opt/mssql
