name: sql-server
services:
    sql-server-2019:
        build:
            dockerfile: DockerFile.sql-server-2019
            context: .
        environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=${CONTAINER_DATABASE_PASSWORD}
        volumes:
        - sqlserver-2019-data:/var/opt/mssql
        
    sql-server-2022:
        build:
            dockerfile: DockerFile.sql-server-2022
            context: .
        environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=${CONTAINER_DATABASE_PASSWORD}
        volumes:
        - sqlserver-2022-data:/var/opt/mssql
