name: azurite
services:
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        volumes:
            - azurite-data:/data
        command: >
          azurite 
          --blobPort 10000 --blobHost 0.0.0.0 
          --queuePort 10001 --queueHost 0.0.0.0 
          --tablePort 10002 --tableHost 0.0.0.0 
          --location /data
          --loose
          --skipApiVersionCheck 
          --disableProductStyleUrl