FROM mcr.microsoft.com/mssql/server:2019-latest

# https://github.com/microsoft/mssql-docker/tree/master/linux/preview/examples/mssql-mlservices

# RUN apt update && apt-get install -y python3 python3-pip r-base

RUN mkdir /var/opt/mssql/bin 
RUN mkdir /var/opt/mssql/backups 
# COPY ./publish/sqlclr/project.* /var/opt/mssql/bin

USER root
RUN chown mssql /var/opt/mssql/bin --recursive
RUN chown mssql /var/opt/mssql/backups --recursive

USER mssql

EXPOSE 1433

CMD ["/opt/mssql/bin/sqlservr"]