name: pgadmin
services:
    pgadmin:
        environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
        - PGADMIN_CONFIG_LOGIN_BANNER="Authorized users only!"
        - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
        volumes:
            - ./pgadmin/servers.json:/pgadmin4/servers.json
        image: dpage/pgadmin4
