
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - ${SERVER_PORT_STIRLING_PDF}:8080
    volumes:
      - stirling-pdf-trainingData:/usr/share/tessdata #Required for extra OCR languages
      - stirling-pdf-extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US