name: ollama
services:
    ollama:
        build:
            dockerfile: DockerFile.ollama
            context: .
        volumes:
        - ollama-models:/root/.ollama/models:rw
        ports:
        - ${SERVER_PORT_OLLAMA}:11434
        restart: 'unless-stopped'