name: sql-server
services:
    sql-server-2019:
        build:
            dockerfile: DockerFile.sql-server-2019
            context: .
        environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
        volumes:
        - sqlserver-data:/var/opt/mssql:rw
        
    sql-server-2022:
        build:
            dockerfile: DockerFile.sql-server-2022
            context: .
        environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
        volumes:
        - sqlserver-data:/var/opt/mssql
