services:
  open-webui:
    build:
        dockerfile: DockerFile.open-webui
        context: .
    volumes:
      - open-webui-data:/app/backend/data:rw
      - open-webui-docs:/app/backend/data/docs:rw
    environment:
      #https://docs.openwebui.com/getting-started/advanced-topics/env-configuration#ollama 
      ENV: dev
      
      DEFAULT_MODELS: 'llama3-70b-8192'
      
      WEBUI_URL: ${OPEN_WEBUI_BASE_URL}
      WEBUI_AUTH: True
      ENABLE_SIGUP: True
      DEFAULT_USER_ROLE: pending
      #WEBHOOK_URL: 


      ## Groq support
      OPENAI_API_BASE_URLS: ${OPENAI_API_BASE_URLS}
      OPENAI_API_KEYS: ${OPENAI_API_KEYS}

      ENABLE_OLLAMA_API: True
      USE_OLLAMA_DOCKER: False
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      
      ## SearNG
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 10
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: ${SEARXNG_QUERY_URL}
      ENABLE_RAG_HYBRID_SEARCH: True

    ## Apache Tika
      PDF_EXTRACT_IMAGES: True
      USE_TIKA: True
      TIKA_SERVER_URL: ${TIKA_SERVER_URL}
      CONTENT_EXTRACTION_ENGINE: tika

  