services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      N8N_HOST: localhost
      N8N_PORT: 5678
      WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_URL}
      N8N_DIAGNOSTICS_ENABLED: false
      N8N_VERSION_NOTIFICATIONS_ENABLED: false
      N8N_TEMPLATES_ENABLED: true
      # EXTERNAL_FRONTEND_HOOKS_URLS: ''
      # N8N_DIAGNOSTICS_CONFIG_FRONTEND: ''
      # N8N_DIAGNOSTICS_CONFIG_BACKEND: ''
      N8N_SECURE_COOKIE: false
    volumes:
    - n8n_data:/home/node/.n8n
