
SETLOCAL
CALL container-config

CALL :DO_RESTORE %CONTAINER_GROUP%-sql-server-1 %MSSQL_NAME% %MSSQL_USER% %MSSQL_PASSWORD%

ENDLOCAL
EXIT /B
GOTO :EOF

:DO_RESTORE

SET CONTAINER_NAME=%1
SET DATABASE_NAME=%2
SET DATABASE_USER_NAME=%3
SET DATABASE_USER_PASSWORD=%4

ECHO -- Restoring Up %DATABASE_NAME%

docker cp %DATABASE_NAME%.bak %CONTAINER_NAME%:/var/opt/mssql/backups/%DATABASE_NAME%.bak

docker exec -it %CONTAINER_NAME% ^
 /opt/mssql-tools18/bin/sqlcmd -S localhost -U %DATABASE_USER_NAME% -P %DATABASE_USER_PASSWORD% -C ^
 -Q "RESTORE DATABASE [%DATABASE_NAME%] FROM  DISK = N'/var/opt/mssql/backups/%DATABASE_NAME%.bak' WITH  FILE = 1,  MOVE N'%DATABASE_NAME%' TO N'/var/opt/mssql/data/%DATABASE_NAME%.mdf',  MOVE N'%DATABASE_NAME%_log' TO N'/var/opt/mssql/data/%DATABASE_NAME%_log.ldf',  NOUNLOAD,  STATS = 5"


EXIT /B
