
@ECHO OFF

SETLOCAL

IF "%BUILD_CONFIGURATION%"=="" SET BUILD_CONFIGURATION=Release

SET PROJECT_PATH_TEST=.\path\testproject\folder
SET PROJECT_PATH_API=.\path\api\folder
SET OUTPUT_PATH=.\publish
SET OUTPUT_PATH_TEST=%OUTPUT_PATH%\test-results
SET OUTPUT_PATH_API=%OUTPUT_PATH%\webapi

ECHO -- Test Builds 
RMDIR /s/q "%OUTPUT_PATH_TEST%" 2>NUL
MKDIR "%OUTPUT_PATH_TEST%"
dotnet test ^
"%PROJECT_PATH_TEST%" ^
--configuration %BUILD_CONFIGURATION% 
SET LAST_ERROR=%ERRORLEVEL%
IF NOT %LAST_ERROR%==0 GOTO :ERROR

ECHO -- Build WebAPI
RMDIR /s/q "%OUTPUT_PATH_API%" 2>NUL
dotnet publish ^
".\%PROJECT_PATH_API%" ^
--configuration %BUILD_CONFIGURATION% ^
--output "%OUTPUT_PATH_API%"
SET LAST_ERROR=%ERRORLEVEL%
IF NOT %LAST_ERROR%==0 GOTO :ERROR

GOTO :EOF

:ERROR
ECHO Error Code: %LAST_ERROR%
EXIT /B %LAST_ERROR%

:EOF
ENDLOCAL